apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fleet-complete-extractor-job
spec:
  schedule: "0 1 * * *" # Every day at 01:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fleet-complete-extractor
            image: path:to:container
            imagePullPolicy: Always
            env:
              - name: DB_NAME
                value: <db_name>
              - name: DB_URL
                value: <db_url>
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: <secret>
                    key: db_password
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: <secret>
                    key: <key>
          restartPolicy: Never
          imagePullSecrets:
            - name: registry-creds
